#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



//constants; some of these numbers correspond with LCD button values
int LEFT_BUTTON = 1;
int CENTER_BUTTON = 2;
int RIGHT_BUTTON = 4;
int RED = LEFT_BUTTON;
int BLUE = RIGHT_BUTTON;
int MATCH = 12;
int SKILLS = CENTER_BUTTON;
int ROBOT_SKILLS = LEFT_BUTTON;
int PROG_SKILLS = RIGHT_BUTTON;
int SIDE = 10;
int TIMING = 20;
int SKILLS_SELECT = 40;
int NO = LEFT_BUTTON;
int YES = RIGHT_BUTTON;
int CONFIRM = CENTER_BUTTON;



int selection;
int question = SIDE;

//autonomous play selection variables
int allianceColor;
bool delayStart;
int skillsMode;
bool selectionDone = false;

void waitForPress() {
	while (nLCDButtons == 0) {
		//wait until a button on the LCD is pressed
	}
}

void waitForRelease() {
	while (nLCDButtons > 0) {
		//wait until no buttons on the LCD are pressed
	}
}

int waitForButtonPress() {
	int btnPressed;
		waitForPress();
		btnPressed = nLCDButtons;
		waitForRelease();
		return btnPressed; //return the buttons that were pressed
}

void resetSelections() {
	question = SIDE;
}

void showQuestion(int type) {
	int choice;
	switch(type) {
	case 10: //side
		displayLCDCenteredString(0, "Which side?");
		displayLCDCenteredString(1, "Red   Sk.   Blue");
		choice = waitForButtonPress();
		if (choice == RED) {
			allianceColor = RED;
			question = TIMING;
			} else if (choice == BLUE) {
			allianceColor = BLUE;
			question = TIMING;
			} else if (choice == SKILLS) {
			question = SKILLS;
		}
		break;
	case 20: //timing
		displayLCDCenteredString(0, "Wait at start?");
		displayLCDCenteredString(1, "No             Yes");
		choice = waitForButtonPress();
		if (choice == NO) {
			delayStart = false;
			question = CONFIRM;
			} else if (choice == YES) {
			delayStart = true;
			question = CONFIRM;
		}
		break;
	case 30: //confirm
		displayLCDCenteredString(0, "Center, confirm");
		displayLCDCenteredString(1, "L/R, start over");
		choice = waitForButtonPress();
		if (choice == CENTER_BUTTON) {
			selectionDone = true;
		} else if (choice == LEFT_BUTTON || choice == RIGHT_BUTTON) {
			resetSelections();
		}
		break;

	case 40: //confirm
		displayLCDCenteredString(0, "Which skills?");
		displayLCDCenteredString(1, "Robot           Prog.");
		choice = waitForButtonPress();
		if (choice == LEFT_BUTTON) {

			selectionDone = true;
		} else if (choice == LEFT_BUTTON || choice == RIGHT_BUTTON) {
			resetSelections();
		}
		break;
	}
}


task main()
{

	while (nPgmTime <= 20000 && !selectionDone) {
		switch(question) {
		case 10: //side
			showQuestion(SIDE);
			break;
		case 20: //timing
			showQuestion(TIMING);
			break;
		case 30: //confirm
			showQuestion(CONFIRM);
			break;
		case 40: //skills
			showQuestion(SKILLS_SELECT);
			break;
		}

	}
}
