#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1) {
		motor[port1] = 100;
		motor[port10] = 100;
		if(abs(SensorValue[I2C_1]) > 0) { //flash LED if IEM is working
			SensorValue[led] = true;
		}
		else if(getMotorVelocity(port1) == 0 && getMotorVelocity(port10) == 0) {
			SensorValue[led] = false;
			SensorValue[I2C_1] = 0; //if it's not or no motors connected, reset IEM readings to allow for more tests
		}
		if (time1[T1] >= 5000) { //auto-reset the green LED every 5 seconds
			SensorValue[led] = false;
			SensorValue[I2C_1] = 0; //if it's not or no motors connected, reset IEM readings to allow for more tests
			time1[T1] = 0;
		}
		wait1Msec(250);
	}


}
