#pragma config(Motor,  port1,           Lintake,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Rintake,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
  while(1 == 1)
  {
    if(vexRT[Btn5U] == 1)
    {
    		motor[Lintake] = 120;
    		motor[Rintake] = 120;
    }
    else if(vexRT[Btn5D] == 1)
    {
    		motor[Lintake] = -120;
    		motor[Rintake] = -120;
    }
    else
    {
    		motor[Lintake] = -0;
    		motor[Rintake] = -0;
  	}
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
