#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           topMotor,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          bottomMotor,   tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//test program to enable PID with default constants for Paper Flywheel

task getRPM() {}

task main()
{
	while(1) {
		//if(vexRT[Btn5D] == 1)
		//{
	//set the other motor to follow the motor with PID activated
	slaveMotor(topMotor, bottomMotor);

	//moveMotorTarget(port10, 7200, 85);
		//}
	}
}
