#pragma config(Sensor, dgtl1,  PneuF1,        sensorDigitalOut)
#pragma config(Sensor, dgtl2,  PneuF2,        sensorDigitalOut)
#pragma config(Sensor, dgtl3,  PneuB1,        sensorDigitalOut)
#pragma config(Sensor, dgtl4,  PneuB2,        sensorDigitalOut)
#pragma config(Motor,  port1,           LBdrive,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LFdrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ramp1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           ramp2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RFdrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RBdrive,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(1 == 1)
  {
  	motor[LBdrive] = vexRT[Ch3];		//sets drive motor speeds to jorsticks
  	motor[LFdrive] = vexRT[Ch3];
  	motor[RBdrive] = vexRT[Ch2];
  	motor[RFdrive] = vexRT[Ch2];

    if(vexRT[Btn5U] == 1)						//intakes balls
    {
    	motor[intake1] = 117;
    	motor[intake2] = 117;
    }
    if (vexRT[Btn5D] == 1)					//outputs balls
    {
    	motor[intake1] = -117;
    	motor[intake2] = -117;
    }
    else														//turns off intake
    {
    	motor[intake1] = 0;
    	motor[intake2] = 0;
    }
    bool ramp;											//creates ramp boolean
    if(vexRT[Btn7L] == 1)						//lowers ramp
    {
    	ramp = true;
    	motor[ramp1] = 110;
    	motor[ramp2] = 110;
    }
    if(vexRT[Btn8R] == 1)						//pulls back ramp
    {
    	ramp = false;
    	motor[ramp1] = -120;
    	motor[ramp2] = -120;
    }
    else
    {
    	if(ramp)											//holds ramp in place
    	{
    	motor[ramp1] = -30;
    	motor[ramp2] = -30;
      }
    }

    if(vexRT[Btn6D] == 1)
    {
    	SensorValue[PneuF1] = 1;
    	SensorValue[PneuF2] = 1;
    	SensorValue[PneuB1] = 1;
    	SensorValue[PneuB2] = 1;
    }

    else
    {
    	SensorValue[PneuF1] = 0;
    	SensorValue[PneuF2] = 0;
    	SensorValue[PneuB1] = 0;
    	SensorValue[PneuB2] = 0;
   	}
    if(!bVEXNETActive)
   	{
   		SensorValue[PneuF1] = 0;
    	SensorValue[PneuF2] = 0;
    	SensorValue[PneuB1] = 0;
    	SensorValue[PneuB2] = 0;
  	}
   }
 }
