#pragma config(Motor,  port1,           LBdrive,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LFdrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ramp1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           ramp2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intake2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RFdrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RBdrive,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(1 == 1)
  {
  	motor[LBdrive] = vexRT[Ch3];
  	motor[LFdrive] = vexRT[Ch3];
  	motor[RBdrive] = vexRT[Ch2];
  	motor[RFdrive] = vexRT[Ch2];

    if(Btn5U == 1)
    {
    	motor[intake1] = 117;
    	motor[intake2] = 117;
    }
    if (Btn5D == 1)
    {
    	motor[intake1] = -117;
    	motor[intake2] = -117;
    }
    else
    {
    	motor[intake1] = 0;
    	motor[intake2] = 0;
    }
  }
}
