#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  led,            sensorNone)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           lDriveFront,   tmotorNone, openLoop)
#pragma config(Motor,  port2,           intake,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lFlyTop,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           lFlyBottom,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           rDriveBack,    tmotorNone, openLoop)
#pragma config(Motor,  port6,           lDriveBack,    tmotorNone, openLoop)
#pragma config(Motor,  port7,           rFlyTop,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rFlyBottom,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port9,           intakeChain,   tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rDriveFront,   tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1) {
		//motor[lFlyTop] = 75;
		//motor[lFlyBottom] = 75;
		//motor[rFlyTop] = 75;
		//motor[rFlyBottom] = 75;
		//wait1Msec(1500);
		motor[intake] = 127;
		motor[intakeChain] = 127;
	}

}
