#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intake1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Fly1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Fly2,          tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           Fly3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftDrive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Fly4,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Fly5,          tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port9,           Fly6,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          intake2,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//constants
float CLICKS_PER_REV = 627.2;
//float CLICKS_PER_METER = ;

void setLeftSpeed (float speed) //sets speed of left flywheel
{
	    motor[Fly1] = speed;
			motor[Fly2] = speed;
			motor[Fly3] = speed;
}

void setRightSpeed (float speed) //sets speed of right flywheel
{
		motor[Fly4] = speed;
		motor[Fly5] = speed;
		motor[Fly6] = speed;
}


void accelerateFlyWheel (float targetSpeed) //gradually increases speed of flywheel
{
	/*while we need to accelerate
	get the current motor speed
	if speed < desired speed
		increase motor power by 10 or (desired speed - speed if that is less than 10)
	continue when motor power = new target speed*/
	bool accelerateOn = false;
	float leftEncVal;
	float rightEncVal;
	float leftRPM;
	float rightRPM;
	float lSpeed = 10;
	float rSpeed = 10; //both left and right speed have to start at 10 to begin the acceleration proccess
	float targetlRPM = lSpeed/127*100; //convert motor speed to RPM
	float targetrRPM = rSpeed/127*100; //convert motor speed to RPM
	bool lAtTarget = false;
	bool rAtTarget = false;
		accelerateOn = vexRT[Btn5D] == 1 ? true : false; //ternary to only switch on when the button is being pressed
		while(accelerateOn)
		{

			setLeftSpeed(lSpeed); //set left side speed to 10
			setRightSpeed(rSpeed); //set right side to 10

			while(!lAtTarget || !rAtTarget) { //only accelerate if at least one side needs to

				//determine how far each side of the flywheel has traveled in .5 sec, so we can approximate RPM
				SensorValue[I2C_1] = 0;
				SensorValue[I2C_2] = 0;
				wait1Msec(500);
				leftEncVal = SensorValue[I2C_1];
				rightEncVal = SensorValue[I2C_2];

				//convert encoder values to approximate RPM
				leftRPM = leftEncVal/CLICKS_PER_REV*120;
				rightRPM = rightEncVal/CLICKS_PER_REV*120;

				//change motor speed as needed for each side
				if(leftRPM >= targetlRPM && lSpeed < targetSpeed) //if the left side is done accelerating from previous loop and is below target speed
				{
						lSpeed += 10; //increase the target speed
						targetlRPM = lSpeed/127*100; //calculate new target RPM
				}
				else {
					if(lSpeed == targetSpeed){
						lAtTarget = true; //this indicates that the left flywheel has reached its target speed
					}
				}

			}
				if(rightRPM >= targetrRPM && rSpeed < targetSpeed) //if the right side is done accelerating from previous loop and is below target speed
				{
						rSpeed += 10; //increase the target speed
						targetrRPM = rSpeed/127*100; //calculate new target RPM
				}
				else {
					rAtTarget = true;  //this indicates that the right flywheel has reached its target speed
				}
			}
		}

task accelerate() { //This task allows us to accelerate the flywheel. It needs to be a seperate task so that we can drive and run the flywheel simultaneously
	while(1)
	{
		if(vexRT[Btn5D] == 1) 
		{
			accelerateFlyWheel(80); //or whatever value... could be set by global variable or something (because there's no other way to get a parameter there)
		}
	}
}

task main()
{
	startTask(accelerate); //starts the flywheel movement code
	while(true)
	{
		motor[leftDrive] = vexRT[Ch3];
		motor[rightDrive] = vexRT[Ch2]; //drive train code
    if(vexRT[Btn5D] == 1 && vexRT[Btn7D] == 1) //only activates flywheel speed 80 is both buttons are pressed 
    {
    	setLeftSpeed(80);
    	setRightSpeed(80);
  }
  else if(vexRT[Btn5U] == 1 && vexRT[Btn7U] == 1) //both buttons pressed activates the speed 65
  {
  		setLeftSpeed(65);
  		setRightSpeed(65);
  }
  else if(vexRT[Btn8U] == 1)
  {
    setLeftSpeed(75);
    setRightSpeed(75);
  }
  else if (vexRT[Btn5U] == 1) {
			setLeftSpeed(60);
			setRightSpeed(60);
	  }
    else
    {
      setLeftSpeed(0);
      setRightSpeed(0);
    }
    if(vexRT[Btn6U] == 1)
    {
    	motor[intake1] = 125;
    	motor[intake2] = 125;
    }
    else if(vexRT[Btn6D] == 1)
    {
    	motor[intake1] = -125;
    	motor[intake2] = -125;
    }
    else
    {
    	motor[intake1] = 0;
    	motor[intake2] = 0;
    }
  }
}
