#pragma config(Motor,  port1,           intake1,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Fly1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Fly2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Fly3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftDrive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Fly4,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Fly5,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Fly6,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          intake2,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[leftDrive] = vexRT[Ch3];
		motor[rightDrive] = vexRT[Ch2];
    if(vexRT[Btn5D] == 1)
    {
     	motor[Fly1] = -80;
			motor[Fly2] = -80;
			motor[Fly3] = -80;
			motor[Fly4] = -80;
			motor[Fly5] = -80;
			motor[Fly6] = -80;
    }
    else
    {
      	motor[Fly1] = 0;
				motor[Fly2] = 0;
				motor[Fly3] = 0;
				motor[Fly4] = 0;
				motor[Fly5] = 0;
				motor[Fly6] = 0;
    }
    if(vexRT[Btn6U] == 1)
    {
    	motor[intake1] = 125;
    	motor[intake2] = 125;
    }
    else if(vexRT[Btn6D] == 1)
    {
    	motor[intake1] = -125;
    	motor[intake2] = -125;
    }
    else
    {
    	motor[intake1] = 0;
    	motor[intake2] = 0;
    }
  }
}
